apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    app.kubernetes.io/part-of: workshop
    app.openshift.io/runtime: mongodb
  name: mongodb-nationalparks
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    name: mongodb-nationalparks
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mongodb-nationalparks
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mongodb-nationalparks
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mongodb-nationalparks
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-admin-password
              name: mongodb-nationalparks
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mongodb-nationalparks
        image: mongodb:5.0
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-nationalparks-data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.ebs.csi.aws.com/zone
                operator: DoesNotExist
              - key: hyperv.node.kubevirt.io/reset
                operator: DoesNotExist
      volumes:
      - name: mongodb-nationalparks-data
        persistentVolumeClaim:
          claimName: mongodb-nationalparks
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mongodb
      from:
        kind: ImageStreamTag
        name: mongodb:5.0
        namespace: openshift
      lastTriggeredImage: mongo:5.0@sha256:f7a950ee4a1cc048300cd3b3da3e939974eb8278525101ac917dbed1a3ce3d51
    type: ImageChange
  - type: ConfigChange

