apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-nationalparks
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# storageClassName: managed-csi
  volumeMode: Filesystem
# volumeName: mongodb-nationalparks
