apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: workshop
    app.kubernetes.io/part-of: workshop
    app.openshift.io/component: parksmap
    component: parksmap
    createdBy: parksmap-template
    role: frontend
  annotations:
    openshift.io/host.generated: 'true'
  name: parksmap
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: parksmap
    weight: 100
  wildcardPolicy: None

