apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: workshop
    component: nationalparks
    createdBy: parksmap-template
    role: backend
    type: parksmap-backend
  annotations:
    openshift.io/host.generated: 'true'
  name: nationalparks
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: nationalparks
    weight: 100
  wildcardPolicy: None
