apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshop
    component: nationalparks
    role: backend
  name: nationalparks
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8787-tcp
    port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    deploymentConfig: nationalparks
  sessionAffinity: None
  type: ClusterIP

