apiVersion: v1
kind: Service
metadata:
  name: mongodb-nationalparks
spec:
  clusterIP: 172.30.252.40
  clusterIPs:
  - 172.30.252.40
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb-nationalparks
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
