apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshop
    component: nationalparks
    createdBy: parksmap-template
    role: backend
    type: parksmap-backend
  annotations:
    service.alpha.openshift.io/dependencies: '[{"name":"mongodb-nationalparks","namespace":"","kind":"Service"}]'
  name: nationalparks
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8787-tcp
    port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    deploymentConfig: nationalparks
  sessionAffinity: None
  type: ClusterIP

