apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
    component: mongodb-nationalparks
    role: database
  name: mongodb-nationalparks
  namespace: parksmap-demo
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb-nationalparks
  sessionAffinity: None
  type: ClusterIP
