apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
  creationTimestamp: "2023-09-09T03:47:32Z"
  labels:
    template: mongodb-ephemeral-template
    template.openshift.io/template-instance-owner: a5f8c8f1-936e-4985-abe4-d9d5a0b55e15
  name: mongodb-nationalparks
  resourceVersion: "278681"
  uid: 23acc389-0044-4545-9196-005c64c2169d
spec:
  clusterIP: 172.30.252.40
  clusterIPs:
  - 172.30.252.40
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb-nationalparks
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
